# Generated by Django 3.2.7 on 2021-09-21 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=120)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pcategory', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=100)),
                ('pdescription', models.CharField(max_length=500)),
                ('pimage', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('pdate_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('poffer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piimages', models.FileField(upload_to='product_pics')),
                ('pioriginal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BestAuto.products')),
            ],
        ),
    ]
